// Code generated by github.com/go-darwin/tools/cmd/mkgodef; DO NOT EDIT.
// Input to cgo -godefs.

//go:build ignore
// +build ignore

package capstone

/*
#include <capstone/bpf.h>
*/
import "C"

type BpfExtType C.enum_bpf_ext_type

const (
	BPF_EXT_INVALID BpfExtType = C.BPF_EXT_INVALID
	BPF_EXT_LEN     BpfExtType = C.BPF_EXT_LEN
)

type BpfInsn C.enum_bpf_insn

const (
	BPF_INS_INVALID BpfInsn = C.BPF_INS_INVALID
	BPF_INS_ADD     BpfInsn = C.BPF_INS_ADD
	BPF_INS_SUB     BpfInsn = C.BPF_INS_SUB
	BPF_INS_MUL     BpfInsn = C.BPF_INS_MUL
	BPF_INS_DIV     BpfInsn = C.BPF_INS_DIV
	BPF_INS_OR      BpfInsn = C.BPF_INS_OR
	BPF_INS_AND     BpfInsn = C.BPF_INS_AND
	BPF_INS_LSH     BpfInsn = C.BPF_INS_LSH
	BPF_INS_RSH     BpfInsn = C.BPF_INS_RSH
	BPF_INS_NEG     BpfInsn = C.BPF_INS_NEG
	BPF_INS_MOD     BpfInsn = C.BPF_INS_MOD
	BPF_INS_XOR     BpfInsn = C.BPF_INS_XOR
	BPF_INS_MOV     BpfInsn = C.BPF_INS_MOV
	BPF_INS_ARSH    BpfInsn = C.BPF_INS_ARSH
	BPF_INS_ADD64   BpfInsn = C.BPF_INS_ADD64
	BPF_INS_SUB64   BpfInsn = C.BPF_INS_SUB64
	BPF_INS_MUL64   BpfInsn = C.BPF_INS_MUL64
	BPF_INS_DIV64   BpfInsn = C.BPF_INS_DIV64
	BPF_INS_OR64    BpfInsn = C.BPF_INS_OR64
	BPF_INS_AND64   BpfInsn = C.BPF_INS_AND64
	BPF_INS_LSH64   BpfInsn = C.BPF_INS_LSH64
	BPF_INS_RSH64   BpfInsn = C.BPF_INS_RSH64
	BPF_INS_NEG64   BpfInsn = C.BPF_INS_NEG64
	BPF_INS_MOD64   BpfInsn = C.BPF_INS_MOD64
	BPF_INS_XOR64   BpfInsn = C.BPF_INS_XOR64
	BPF_INS_MOV64   BpfInsn = C.BPF_INS_MOV64
	BPF_INS_ARSH64  BpfInsn = C.BPF_INS_ARSH64
	BPF_INS_LE16    BpfInsn = C.BPF_INS_LE16
	BPF_INS_LE32    BpfInsn = C.BPF_INS_LE32
	BPF_INS_LE64    BpfInsn = C.BPF_INS_LE64
	BPF_INS_BE16    BpfInsn = C.BPF_INS_BE16
	BPF_INS_BE32    BpfInsn = C.BPF_INS_BE32
	BPF_INS_BE64    BpfInsn = C.BPF_INS_BE64
	BPF_INS_LDW     BpfInsn = C.BPF_INS_LDW
	BPF_INS_LDH     BpfInsn = C.BPF_INS_LDH
	BPF_INS_LDB     BpfInsn = C.BPF_INS_LDB
	BPF_INS_LDDW    BpfInsn = C.BPF_INS_LDDW
	BPF_INS_LDXW    BpfInsn = C.BPF_INS_LDXW
	BPF_INS_LDXH    BpfInsn = C.BPF_INS_LDXH
	BPF_INS_LDXB    BpfInsn = C.BPF_INS_LDXB
	BPF_INS_LDXDW   BpfInsn = C.BPF_INS_LDXDW
	BPF_INS_STW     BpfInsn = C.BPF_INS_STW
	BPF_INS_STH     BpfInsn = C.BPF_INS_STH
	BPF_INS_STB     BpfInsn = C.BPF_INS_STB
	BPF_INS_STDW    BpfInsn = C.BPF_INS_STDW
	BPF_INS_STXW    BpfInsn = C.BPF_INS_STXW
	BPF_INS_STXH    BpfInsn = C.BPF_INS_STXH
	BPF_INS_STXB    BpfInsn = C.BPF_INS_STXB
	BPF_INS_STXDW   BpfInsn = C.BPF_INS_STXDW
	BPF_INS_XADDW   BpfInsn = C.BPF_INS_XADDW
	BPF_INS_XADDDW  BpfInsn = C.BPF_INS_XADDDW
	BPF_INS_JMP     BpfInsn = C.BPF_INS_JMP
	BPF_INS_JEQ     BpfInsn = C.BPF_INS_JEQ
	BPF_INS_JGT     BpfInsn = C.BPF_INS_JGT
	BPF_INS_JGE     BpfInsn = C.BPF_INS_JGE
	BPF_INS_JSET    BpfInsn = C.BPF_INS_JSET
	BPF_INS_JNE     BpfInsn = C.BPF_INS_JNE
	BPF_INS_JSGT    BpfInsn = C.BPF_INS_JSGT
	BPF_INS_JSGE    BpfInsn = C.BPF_INS_JSGE
	BPF_INS_CALL    BpfInsn = C.BPF_INS_CALL
	BPF_INS_EXIT    BpfInsn = C.BPF_INS_EXIT
	BPF_INS_JLT     BpfInsn = C.BPF_INS_JLT
	BPF_INS_JLE     BpfInsn = C.BPF_INS_JLE
	BPF_INS_JSLT    BpfInsn = C.BPF_INS_JSLT
	BPF_INS_JSLE    BpfInsn = C.BPF_INS_JSLE
	BPF_INS_RET     BpfInsn = C.BPF_INS_RET
	BPF_INS_TAX     BpfInsn = C.BPF_INS_TAX
	BPF_INS_TXA     BpfInsn = C.BPF_INS_TXA
	BPF_INS_ENDING  BpfInsn = C.BPF_INS_ENDING
	BPF_INS_LD      BpfInsn = C.BPF_INS_LD
	BPF_INS_LDX     BpfInsn = C.BPF_INS_LDX
	BPF_INS_ST      BpfInsn = C.BPF_INS_ST
	BPF_INS_STX     BpfInsn = C.BPF_INS_STX
)

type BpfInsnGroup C.enum_bpf_insn_group

const (
	BPF_GRP_INVALID BpfInsnGroup = C.BPF_GRP_INVALID
	BPF_GRP_LOAD    BpfInsnGroup = C.BPF_GRP_LOAD
	BPF_GRP_STORE   BpfInsnGroup = C.BPF_GRP_STORE
	BPF_GRP_ALU     BpfInsnGroup = C.BPF_GRP_ALU
	BPF_GRP_JUMP    BpfInsnGroup = C.BPF_GRP_JUMP
	BPF_GRP_CALL    BpfInsnGroup = C.BPF_GRP_CALL
	BPF_GRP_RETURN  BpfInsnGroup = C.BPF_GRP_RETURN
	BPF_GRP_MISC    BpfInsnGroup = C.BPF_GRP_MISC
	BPF_GRP_ENDING  BpfInsnGroup = C.BPF_GRP_ENDING
)

type BpfOpType C.enum_bpf_op_type

const (
	BPF_OP_INVALID BpfOpType = C.BPF_OP_INVALID
	BPF_OP_REG     BpfOpType = C.BPF_OP_REG
	BPF_OP_IMM     BpfOpType = C.BPF_OP_IMM
	BPF_OP_OFF     BpfOpType = C.BPF_OP_OFF
	BPF_OP_MEM     BpfOpType = C.BPF_OP_MEM
	BPF_OP_MMEM    BpfOpType = C.BPF_OP_MMEM
	BPF_OP_MSH     BpfOpType = C.BPF_OP_MSH
	BPF_OP_EXT     BpfOpType = C.BPF_OP_EXT
)

type BpfReg C.enum_bpf_reg

const (
	BPF_REG_INVALID BpfReg = C.BPF_REG_INVALID
	BPF_REG_A       BpfReg = C.BPF_REG_A
	BPF_REG_X       BpfReg = C.BPF_REG_X
	BPF_REG_R0      BpfReg = C.BPF_REG_R0
	BPF_REG_R1      BpfReg = C.BPF_REG_R1
	BPF_REG_R2      BpfReg = C.BPF_REG_R2
	BPF_REG_R3      BpfReg = C.BPF_REG_R3
	BPF_REG_R4      BpfReg = C.BPF_REG_R4
	BPF_REG_R5      BpfReg = C.BPF_REG_R5
	BPF_REG_R6      BpfReg = C.BPF_REG_R6
	BPF_REG_R7      BpfReg = C.BPF_REG_R7
	BPF_REG_R8      BpfReg = C.BPF_REG_R8
	BPF_REG_R9      BpfReg = C.BPF_REG_R9
	BPF_REG_R10     BpfReg = C.BPF_REG_R10
	BPF_REG_ENDING  BpfReg = C.BPF_REG_ENDING
)

type BpfOpMem C.struct_bpf_op_mem

type CsBpf C.struct_cs_bpf

type CsBpfOp C.struct_cs_bpf_op
