// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs mos65xx_unix.go

package capstone

type Mos65XxAddressMode uint32

const (
	MOS65XX_AM_NONE          Mos65XxAddressMode = 0x0
	MOS65XX_AM_IMP           Mos65XxAddressMode = 0x1
	MOS65XX_AM_ACC           Mos65XxAddressMode = 0x2
	MOS65XX_AM_IMM           Mos65XxAddressMode = 0x3
	MOS65XX_AM_REL           Mos65XxAddressMode = 0x4
	MOS65XX_AM_INT           Mos65XxAddressMode = 0x5
	MOS65XX_AM_BLOCK         Mos65XxAddressMode = 0x6
	MOS65XX_AM_ZP            Mos65XxAddressMode = 0x7
	MOS65XX_AM_ZP_X          Mos65XxAddressMode = 0x8
	MOS65XX_AM_ZP_Y          Mos65XxAddressMode = 0x9
	MOS65XX_AM_ZP_REL        Mos65XxAddressMode = 0xa
	MOS65XX_AM_ZP_IND        Mos65XxAddressMode = 0xb
	MOS65XX_AM_ZP_X_IND      Mos65XxAddressMode = 0xc
	MOS65XX_AM_ZP_IND_Y      Mos65XxAddressMode = 0xd
	MOS65XX_AM_ZP_IND_LONG   Mos65XxAddressMode = 0xe
	MOS65XX_AM_ZP_IND_LONG_Y Mos65XxAddressMode = 0xf
	MOS65XX_AM_ABS           Mos65XxAddressMode = 0x10
	MOS65XX_AM_ABS_X         Mos65XxAddressMode = 0x11
	MOS65XX_AM_ABS_Y         Mos65XxAddressMode = 0x12
	MOS65XX_AM_ABS_IND       Mos65XxAddressMode = 0x13
	MOS65XX_AM_ABS_X_IND     Mos65XxAddressMode = 0x14
	MOS65XX_AM_ABS_IND_LONG  Mos65XxAddressMode = 0x15
	MOS65XX_AM_ABS_LONG      Mos65XxAddressMode = 0x16
	MOS65XX_AM_ABS_LONG_X    Mos65XxAddressMode = 0x17
	MOS65XX_AM_SR            Mos65XxAddressMode = 0x18
	MOS65XX_AM_SR_IND_Y      Mos65XxAddressMode = 0x19
)

type Mos65XxGroupType uint32

const (
	MOS65XX_GRP_INVALID         Mos65XxGroupType = 0x0
	MOS65XX_GRP_JUMP            Mos65XxGroupType = 0x1
	MOS65XX_GRP_CALL            Mos65XxGroupType = 0x2
	MOS65XX_GRP_RET             Mos65XxGroupType = 0x3
	MOS65XX_GRP_INT             Mos65XxGroupType = 0x4
	MOS65XX_GRP_IRET            Mos65XxGroupType = 0x5
	MOS65XX_GRP_BRANCH_RELATIVE Mos65XxGroupType = 0x6
	MOS65XX_GRP_ENDING          Mos65XxGroupType = 0x7
)

type Mos65XxInsn uint32

const (
	MOS65XX_INS_INVALID Mos65XxInsn = 0x0
	MOS65XX_INS_ADC     Mos65XxInsn = 0x1
	MOS65XX_INS_AND     Mos65XxInsn = 0x2
	MOS65XX_INS_ASL     Mos65XxInsn = 0x3
	MOS65XX_INS_BBR     Mos65XxInsn = 0x4
	MOS65XX_INS_BBS     Mos65XxInsn = 0x5
	MOS65XX_INS_BCC     Mos65XxInsn = 0x6
	MOS65XX_INS_BCS     Mos65XxInsn = 0x7
	MOS65XX_INS_BEQ     Mos65XxInsn = 0x8
	MOS65XX_INS_BIT     Mos65XxInsn = 0x9
	MOS65XX_INS_BMI     Mos65XxInsn = 0xa
	MOS65XX_INS_BNE     Mos65XxInsn = 0xb
	MOS65XX_INS_BPL     Mos65XxInsn = 0xc
	MOS65XX_INS_BRA     Mos65XxInsn = 0xd
	MOS65XX_INS_BRK     Mos65XxInsn = 0xe
	MOS65XX_INS_BRL     Mos65XxInsn = 0xf
	MOS65XX_INS_BVC     Mos65XxInsn = 0x10
	MOS65XX_INS_BVS     Mos65XxInsn = 0x11
	MOS65XX_INS_CLC     Mos65XxInsn = 0x12
	MOS65XX_INS_CLD     Mos65XxInsn = 0x13
	MOS65XX_INS_CLI     Mos65XxInsn = 0x14
	MOS65XX_INS_CLV     Mos65XxInsn = 0x15
	MOS65XX_INS_CMP     Mos65XxInsn = 0x16
	MOS65XX_INS_COP     Mos65XxInsn = 0x17
	MOS65XX_INS_CPX     Mos65XxInsn = 0x18
	MOS65XX_INS_CPY     Mos65XxInsn = 0x19
	MOS65XX_INS_DEC     Mos65XxInsn = 0x1a
	MOS65XX_INS_DEX     Mos65XxInsn = 0x1b
	MOS65XX_INS_DEY     Mos65XxInsn = 0x1c
	MOS65XX_INS_EOR     Mos65XxInsn = 0x1d
	MOS65XX_INS_INC     Mos65XxInsn = 0x1e
	MOS65XX_INS_INX     Mos65XxInsn = 0x1f
	MOS65XX_INS_INY     Mos65XxInsn = 0x20
	MOS65XX_INS_JML     Mos65XxInsn = 0x21
	MOS65XX_INS_JMP     Mos65XxInsn = 0x22
	MOS65XX_INS_JSL     Mos65XxInsn = 0x23
	MOS65XX_INS_JSR     Mos65XxInsn = 0x24
	MOS65XX_INS_LDA     Mos65XxInsn = 0x25
	MOS65XX_INS_LDX     Mos65XxInsn = 0x26
	MOS65XX_INS_LDY     Mos65XxInsn = 0x27
	MOS65XX_INS_LSR     Mos65XxInsn = 0x28
	MOS65XX_INS_MVN     Mos65XxInsn = 0x29
	MOS65XX_INS_MVP     Mos65XxInsn = 0x2a
	MOS65XX_INS_NOP     Mos65XxInsn = 0x2b
	MOS65XX_INS_ORA     Mos65XxInsn = 0x2c
	MOS65XX_INS_PEA     Mos65XxInsn = 0x2d
	MOS65XX_INS_PEI     Mos65XxInsn = 0x2e
	MOS65XX_INS_PER     Mos65XxInsn = 0x2f
	MOS65XX_INS_PHA     Mos65XxInsn = 0x30
	MOS65XX_INS_PHB     Mos65XxInsn = 0x31
	MOS65XX_INS_PHD     Mos65XxInsn = 0x32
	MOS65XX_INS_PHK     Mos65XxInsn = 0x33
	MOS65XX_INS_PHP     Mos65XxInsn = 0x34
	MOS65XX_INS_PHX     Mos65XxInsn = 0x35
	MOS65XX_INS_PHY     Mos65XxInsn = 0x36
	MOS65XX_INS_PLA     Mos65XxInsn = 0x37
	MOS65XX_INS_PLB     Mos65XxInsn = 0x38
	MOS65XX_INS_PLD     Mos65XxInsn = 0x39
	MOS65XX_INS_PLP     Mos65XxInsn = 0x3a
	MOS65XX_INS_PLX     Mos65XxInsn = 0x3b
	MOS65XX_INS_PLY     Mos65XxInsn = 0x3c
	MOS65XX_INS_REP     Mos65XxInsn = 0x3d
	MOS65XX_INS_RMB     Mos65XxInsn = 0x3e
	MOS65XX_INS_ROL     Mos65XxInsn = 0x3f
	MOS65XX_INS_ROR     Mos65XxInsn = 0x40
	MOS65XX_INS_RTI     Mos65XxInsn = 0x41
	MOS65XX_INS_RTL     Mos65XxInsn = 0x42
	MOS65XX_INS_RTS     Mos65XxInsn = 0x43
	MOS65XX_INS_SBC     Mos65XxInsn = 0x44
	MOS65XX_INS_SEC     Mos65XxInsn = 0x45
	MOS65XX_INS_SED     Mos65XxInsn = 0x46
	MOS65XX_INS_SEI     Mos65XxInsn = 0x47
	MOS65XX_INS_SEP     Mos65XxInsn = 0x48
	MOS65XX_INS_SMB     Mos65XxInsn = 0x49
	MOS65XX_INS_STA     Mos65XxInsn = 0x4a
	MOS65XX_INS_STP     Mos65XxInsn = 0x4b
	MOS65XX_INS_STX     Mos65XxInsn = 0x4c
	MOS65XX_INS_STY     Mos65XxInsn = 0x4d
	MOS65XX_INS_STZ     Mos65XxInsn = 0x4e
	MOS65XX_INS_TAX     Mos65XxInsn = 0x4f
	MOS65XX_INS_TAY     Mos65XxInsn = 0x50
	MOS65XX_INS_TCD     Mos65XxInsn = 0x51
	MOS65XX_INS_TCS     Mos65XxInsn = 0x52
	MOS65XX_INS_TDC     Mos65XxInsn = 0x53
	MOS65XX_INS_TRB     Mos65XxInsn = 0x54
	MOS65XX_INS_TSB     Mos65XxInsn = 0x55
	MOS65XX_INS_TSC     Mos65XxInsn = 0x56
	MOS65XX_INS_TSX     Mos65XxInsn = 0x57
	MOS65XX_INS_TXA     Mos65XxInsn = 0x58
	MOS65XX_INS_TXS     Mos65XxInsn = 0x59
	MOS65XX_INS_TXY     Mos65XxInsn = 0x5a
	MOS65XX_INS_TYA     Mos65XxInsn = 0x5b
	MOS65XX_INS_TYX     Mos65XxInsn = 0x5c
	MOS65XX_INS_WAI     Mos65XxInsn = 0x5d
	MOS65XX_INS_WDM     Mos65XxInsn = 0x5e
	MOS65XX_INS_XBA     Mos65XxInsn = 0x5f
	MOS65XX_INS_XCE     Mos65XxInsn = 0x60
	MOS65XX_INS_ENDING  Mos65XxInsn = 0x61
)

type Mos65XxOpType uint32

const (
	MOS65XX_OP_INVALID Mos65XxOpType = 0x0
	MOS65XX_OP_REG     Mos65XxOpType = 0x1
	MOS65XX_OP_IMM     Mos65XxOpType = 0x2
	MOS65XX_OP_MEM     Mos65XxOpType = 0x3
)

type Mos65XxReg uint32

const (
	MOS65XX_REG_INVALID Mos65XxReg = 0x0
	MOS65XX_REG_ACC     Mos65XxReg = 0x1
	MOS65XX_REG_X       Mos65XxReg = 0x2
	MOS65XX_REG_Y       Mos65XxReg = 0x3
	MOS65XX_REG_P       Mos65XxReg = 0x4
	MOS65XX_REG_SP      Mos65XxReg = 0x5
	MOS65XX_REG_DP      Mos65XxReg = 0x6
	MOS65XX_REG_B       Mos65XxReg = 0x7
	MOS65XX_REG_K       Mos65XxReg = 0x8
	MOS65XX_REG_ENDING  Mos65XxReg = 0x9
)

type CsMos65Xx struct {
	Am             uint32
	Modifies_flags bool
	Op_count       uint8
	Operands       [3]CsMos65XxOp
}

type CsMos65XxOp struct {
	Type uint32
	Reg  uint32
}
