// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs evm_unix.go

package capstone

type EvmInsn uint32

const (
	EVM_INS_STOP           EvmInsn = 0x0
	EVM_INS_ADD            EvmInsn = 0x1
	EVM_INS_MUL            EvmInsn = 0x2
	EVM_INS_SUB            EvmInsn = 0x3
	EVM_INS_DIV            EvmInsn = 0x4
	EVM_INS_SDIV           EvmInsn = 0x5
	EVM_INS_MOD            EvmInsn = 0x6
	EVM_INS_SMOD           EvmInsn = 0x7
	EVM_INS_ADDMOD         EvmInsn = 0x8
	EVM_INS_MULMOD         EvmInsn = 0x9
	EVM_INS_EXP            EvmInsn = 0xa
	EVM_INS_SIGNEXTEND     EvmInsn = 0xb
	EVM_INS_LT             EvmInsn = 0x10
	EVM_INS_GT             EvmInsn = 0x11
	EVM_INS_SLT            EvmInsn = 0x12
	EVM_INS_SGT            EvmInsn = 0x13
	EVM_INS_EQ             EvmInsn = 0x14
	EVM_INS_ISZERO         EvmInsn = 0x15
	EVM_INS_AND            EvmInsn = 0x16
	EVM_INS_OR             EvmInsn = 0x17
	EVM_INS_XOR            EvmInsn = 0x18
	EVM_INS_NOT            EvmInsn = 0x19
	EVM_INS_BYTE           EvmInsn = 0x1a
	EVM_INS_SHA3           EvmInsn = 0x20
	EVM_INS_ADDRESS        EvmInsn = 0x30
	EVM_INS_BALANCE        EvmInsn = 0x31
	EVM_INS_ORIGIN         EvmInsn = 0x32
	EVM_INS_CALLER         EvmInsn = 0x33
	EVM_INS_CALLVALUE      EvmInsn = 0x34
	EVM_INS_CALLDATALOAD   EvmInsn = 0x35
	EVM_INS_CALLDATASIZE   EvmInsn = 0x36
	EVM_INS_CALLDATACOPY   EvmInsn = 0x37
	EVM_INS_CODESIZE       EvmInsn = 0x38
	EVM_INS_CODECOPY       EvmInsn = 0x39
	EVM_INS_GASPRICE       EvmInsn = 0x3a
	EVM_INS_EXTCODESIZE    EvmInsn = 0x3b
	EVM_INS_EXTCODECOPY    EvmInsn = 0x3c
	EVM_INS_RETURNDATASIZE EvmInsn = 0x3d
	EVM_INS_RETURNDATACOPY EvmInsn = 0x3e
	EVM_INS_BLOCKHASH      EvmInsn = 0x40
	EVM_INS_COINBASE       EvmInsn = 0x41
	EVM_INS_TIMESTAMP      EvmInsn = 0x42
	EVM_INS_NUMBER         EvmInsn = 0x43
	EVM_INS_DIFFICULTY     EvmInsn = 0x44
	EVM_INS_GASLIMIT       EvmInsn = 0x45
	EVM_INS_POP            EvmInsn = 0x50
	EVM_INS_MLOAD          EvmInsn = 0x51
	EVM_INS_MSTORE         EvmInsn = 0x52
	EVM_INS_MSTORE8        EvmInsn = 0x53
	EVM_INS_SLOAD          EvmInsn = 0x54
	EVM_INS_SSTORE         EvmInsn = 0x55
	EVM_INS_JUMP           EvmInsn = 0x56
	EVM_INS_JUMPI          EvmInsn = 0x57
	EVM_INS_PC             EvmInsn = 0x58
	EVM_INS_MSIZE          EvmInsn = 0x59
	EVM_INS_GAS            EvmInsn = 0x5a
	EVM_INS_JUMPDEST       EvmInsn = 0x5b
	EVM_INS_PUSH1          EvmInsn = 0x60
	EVM_INS_PUSH2          EvmInsn = 0x61
	EVM_INS_PUSH3          EvmInsn = 0x62
	EVM_INS_PUSH4          EvmInsn = 0x63
	EVM_INS_PUSH5          EvmInsn = 0x64
	EVM_INS_PUSH6          EvmInsn = 0x65
	EVM_INS_PUSH7          EvmInsn = 0x66
	EVM_INS_PUSH8          EvmInsn = 0x67
	EVM_INS_PUSH9          EvmInsn = 0x68
	EVM_INS_PUSH10         EvmInsn = 0x69
	EVM_INS_PUSH11         EvmInsn = 0x6a
	EVM_INS_PUSH12         EvmInsn = 0x6b
	EVM_INS_PUSH13         EvmInsn = 0x6c
	EVM_INS_PUSH14         EvmInsn = 0x6d
	EVM_INS_PUSH15         EvmInsn = 0x6e
	EVM_INS_PUSH16         EvmInsn = 0x6f
	EVM_INS_PUSH17         EvmInsn = 0x70
	EVM_INS_PUSH18         EvmInsn = 0x71
	EVM_INS_PUSH19         EvmInsn = 0x72
	EVM_INS_PUSH20         EvmInsn = 0x73
	EVM_INS_PUSH21         EvmInsn = 0x74
	EVM_INS_PUSH22         EvmInsn = 0x75
	EVM_INS_PUSH23         EvmInsn = 0x76
	EVM_INS_PUSH24         EvmInsn = 0x77
	EVM_INS_PUSH25         EvmInsn = 0x78
	EVM_INS_PUSH26         EvmInsn = 0x79
	EVM_INS_PUSH27         EvmInsn = 0x7a
	EVM_INS_PUSH28         EvmInsn = 0x7b
	EVM_INS_PUSH29         EvmInsn = 0x7c
	EVM_INS_PUSH30         EvmInsn = 0x7d
	EVM_INS_PUSH31         EvmInsn = 0x7e
	EVM_INS_PUSH32         EvmInsn = 0x7f
	EVM_INS_DUP1           EvmInsn = 0x80
	EVM_INS_DUP2           EvmInsn = 0x81
	EVM_INS_DUP3           EvmInsn = 0x82
	EVM_INS_DUP4           EvmInsn = 0x83
	EVM_INS_DUP5           EvmInsn = 0x84
	EVM_INS_DUP6           EvmInsn = 0x85
	EVM_INS_DUP7           EvmInsn = 0x86
	EVM_INS_DUP8           EvmInsn = 0x87
	EVM_INS_DUP9           EvmInsn = 0x88
	EVM_INS_DUP10          EvmInsn = 0x89
	EVM_INS_DUP11          EvmInsn = 0x8a
	EVM_INS_DUP12          EvmInsn = 0x8b
	EVM_INS_DUP13          EvmInsn = 0x8c
	EVM_INS_DUP14          EvmInsn = 0x8d
	EVM_INS_DUP15          EvmInsn = 0x8e
	EVM_INS_DUP16          EvmInsn = 0x8f
	EVM_INS_SWAP1          EvmInsn = 0x90
	EVM_INS_SWAP2          EvmInsn = 0x91
	EVM_INS_SWAP3          EvmInsn = 0x92
	EVM_INS_SWAP4          EvmInsn = 0x93
	EVM_INS_SWAP5          EvmInsn = 0x94
	EVM_INS_SWAP6          EvmInsn = 0x95
	EVM_INS_SWAP7          EvmInsn = 0x96
	EVM_INS_SWAP8          EvmInsn = 0x97
	EVM_INS_SWAP9          EvmInsn = 0x98
	EVM_INS_SWAP10         EvmInsn = 0x99
	EVM_INS_SWAP11         EvmInsn = 0x9a
	EVM_INS_SWAP12         EvmInsn = 0x9b
	EVM_INS_SWAP13         EvmInsn = 0x9c
	EVM_INS_SWAP14         EvmInsn = 0x9d
	EVM_INS_SWAP15         EvmInsn = 0x9e
	EVM_INS_SWAP16         EvmInsn = 0x9f
	EVM_INS_LOG0           EvmInsn = 0xa0
	EVM_INS_LOG1           EvmInsn = 0xa1
	EVM_INS_LOG2           EvmInsn = 0xa2
	EVM_INS_LOG3           EvmInsn = 0xa3
	EVM_INS_LOG4           EvmInsn = 0xa4
	EVM_INS_CREATE         EvmInsn = 0xf0
	EVM_INS_CALL           EvmInsn = 0xf1
	EVM_INS_CALLCODE       EvmInsn = 0xf2
	EVM_INS_RETURN         EvmInsn = 0xf3
	EVM_INS_DELEGATECALL   EvmInsn = 0xf4
	EVM_INS_CALLBLACKBOX   EvmInsn = 0xf5
	EVM_INS_STATICCALL     EvmInsn = 0xfa
	EVM_INS_REVERT         EvmInsn = 0xfd
	EVM_INS_SUICIDE        EvmInsn = 0xff
	EVM_INS_INVALID        EvmInsn = 0x200
	EVM_INS_ENDING         EvmInsn = 0x201
)

type EvmInsnGroup uint32

const (
	EVM_GRP_INVALID     EvmInsnGroup = 0x0
	EVM_GRP_JUMP        EvmInsnGroup = 0x1
	EVM_GRP_MATH        EvmInsnGroup = 0x8
	EVM_GRP_STACK_WRITE EvmInsnGroup = 0x9
	EVM_GRP_STACK_READ  EvmInsnGroup = 0xa
	EVM_GRP_MEM_WRITE   EvmInsnGroup = 0xb
	EVM_GRP_MEM_READ    EvmInsnGroup = 0xc
	EVM_GRP_STORE_WRITE EvmInsnGroup = 0xd
	EVM_GRP_STORE_READ  EvmInsnGroup = 0xe
	EVM_GRP_HALT        EvmInsnGroup = 0xf
	EVM_GRP_ENDING      EvmInsnGroup = 0x10
)

type CsEvm struct {
	Pop  uint8
	Push uint8
	Fee  uint32
}
