// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs xcore_unix.go

package capstone

type XcoreInsn uint32

const (
	XCORE_INS_INVALID XcoreInsn = 0x0
	XCORE_INS_ADD     XcoreInsn = 0x1
	XCORE_INS_ANDNOT  XcoreInsn = 0x2
	XCORE_INS_AND     XcoreInsn = 0x3
	XCORE_INS_ASHR    XcoreInsn = 0x4
	XCORE_INS_BAU     XcoreInsn = 0x5
	XCORE_INS_BITREV  XcoreInsn = 0x6
	XCORE_INS_BLA     XcoreInsn = 0x7
	XCORE_INS_BLAT    XcoreInsn = 0x8
	XCORE_INS_BL      XcoreInsn = 0x9
	XCORE_INS_BF      XcoreInsn = 0xa
	XCORE_INS_BT      XcoreInsn = 0xb
	XCORE_INS_BU      XcoreInsn = 0xc
	XCORE_INS_BRU     XcoreInsn = 0xd
	XCORE_INS_BYTEREV XcoreInsn = 0xe
	XCORE_INS_CHKCT   XcoreInsn = 0xf
	XCORE_INS_CLRE    XcoreInsn = 0x10
	XCORE_INS_CLRPT   XcoreInsn = 0x11
	XCORE_INS_CLRSR   XcoreInsn = 0x12
	XCORE_INS_CLZ     XcoreInsn = 0x13
	XCORE_INS_CRC8    XcoreInsn = 0x14
	XCORE_INS_CRC32   XcoreInsn = 0x15
	XCORE_INS_DCALL   XcoreInsn = 0x16
	XCORE_INS_DENTSP  XcoreInsn = 0x17
	XCORE_INS_DGETREG XcoreInsn = 0x18
	XCORE_INS_DIVS    XcoreInsn = 0x19
	XCORE_INS_DIVU    XcoreInsn = 0x1a
	XCORE_INS_DRESTSP XcoreInsn = 0x1b
	XCORE_INS_DRET    XcoreInsn = 0x1c
	XCORE_INS_ECALLF  XcoreInsn = 0x1d
	XCORE_INS_ECALLT  XcoreInsn = 0x1e
	XCORE_INS_EDU     XcoreInsn = 0x1f
	XCORE_INS_EEF     XcoreInsn = 0x20
	XCORE_INS_EET     XcoreInsn = 0x21
	XCORE_INS_EEU     XcoreInsn = 0x22
	XCORE_INS_ENDIN   XcoreInsn = 0x23
	XCORE_INS_ENTSP   XcoreInsn = 0x24
	XCORE_INS_EQ      XcoreInsn = 0x25
	XCORE_INS_EXTDP   XcoreInsn = 0x26
	XCORE_INS_EXTSP   XcoreInsn = 0x27
	XCORE_INS_FREER   XcoreInsn = 0x28
	XCORE_INS_FREET   XcoreInsn = 0x29
	XCORE_INS_GETD    XcoreInsn = 0x2a
	XCORE_INS_GET     XcoreInsn = 0x2b
	XCORE_INS_GETN    XcoreInsn = 0x2c
	XCORE_INS_GETR    XcoreInsn = 0x2d
	XCORE_INS_GETSR   XcoreInsn = 0x2e
	XCORE_INS_GETST   XcoreInsn = 0x2f
	XCORE_INS_GETTS   XcoreInsn = 0x30
	XCORE_INS_INCT    XcoreInsn = 0x31
	XCORE_INS_INIT    XcoreInsn = 0x32
	XCORE_INS_INPW    XcoreInsn = 0x33
	XCORE_INS_INSHR   XcoreInsn = 0x34
	XCORE_INS_INT     XcoreInsn = 0x35
	XCORE_INS_IN      XcoreInsn = 0x36
	XCORE_INS_KCALL   XcoreInsn = 0x37
	XCORE_INS_KENTSP  XcoreInsn = 0x38
	XCORE_INS_KRESTSP XcoreInsn = 0x39
	XCORE_INS_KRET    XcoreInsn = 0x3a
	XCORE_INS_LADD    XcoreInsn = 0x3b
	XCORE_INS_LD16S   XcoreInsn = 0x3c
	XCORE_INS_LD8U    XcoreInsn = 0x3d
	XCORE_INS_LDA16   XcoreInsn = 0x3e
	XCORE_INS_LDAP    XcoreInsn = 0x3f
	XCORE_INS_LDAW    XcoreInsn = 0x40
	XCORE_INS_LDC     XcoreInsn = 0x41
	XCORE_INS_LDW     XcoreInsn = 0x42
	XCORE_INS_LDIVU   XcoreInsn = 0x43
	XCORE_INS_LMUL    XcoreInsn = 0x44
	XCORE_INS_LSS     XcoreInsn = 0x45
	XCORE_INS_LSUB    XcoreInsn = 0x46
	XCORE_INS_LSU     XcoreInsn = 0x47
	XCORE_INS_MACCS   XcoreInsn = 0x48
	XCORE_INS_MACCU   XcoreInsn = 0x49
	XCORE_INS_MJOIN   XcoreInsn = 0x4a
	XCORE_INS_MKMSK   XcoreInsn = 0x4b
	XCORE_INS_MSYNC   XcoreInsn = 0x4c
	XCORE_INS_MUL     XcoreInsn = 0x4d
	XCORE_INS_NEG     XcoreInsn = 0x4e
	XCORE_INS_NOT     XcoreInsn = 0x4f
	XCORE_INS_OR      XcoreInsn = 0x50
	XCORE_INS_OUTCT   XcoreInsn = 0x51
	XCORE_INS_OUTPW   XcoreInsn = 0x52
	XCORE_INS_OUTSHR  XcoreInsn = 0x53
	XCORE_INS_OUTT    XcoreInsn = 0x54
	XCORE_INS_OUT     XcoreInsn = 0x55
	XCORE_INS_PEEK    XcoreInsn = 0x56
	XCORE_INS_REMS    XcoreInsn = 0x57
	XCORE_INS_REMU    XcoreInsn = 0x58
	XCORE_INS_RETSP   XcoreInsn = 0x59
	XCORE_INS_SETCLK  XcoreInsn = 0x5a
	XCORE_INS_SET     XcoreInsn = 0x5b
	XCORE_INS_SETC    XcoreInsn = 0x5c
	XCORE_INS_SETD    XcoreInsn = 0x5d
	XCORE_INS_SETEV   XcoreInsn = 0x5e
	XCORE_INS_SETN    XcoreInsn = 0x5f
	XCORE_INS_SETPSC  XcoreInsn = 0x60
	XCORE_INS_SETPT   XcoreInsn = 0x61
	XCORE_INS_SETRDY  XcoreInsn = 0x62
	XCORE_INS_SETSR   XcoreInsn = 0x63
	XCORE_INS_SETTW   XcoreInsn = 0x64
	XCORE_INS_SETV    XcoreInsn = 0x65
	XCORE_INS_SEXT    XcoreInsn = 0x66
	XCORE_INS_SHL     XcoreInsn = 0x67
	XCORE_INS_SHR     XcoreInsn = 0x68
	XCORE_INS_SSYNC   XcoreInsn = 0x69
	XCORE_INS_ST16    XcoreInsn = 0x6a
	XCORE_INS_ST8     XcoreInsn = 0x6b
	XCORE_INS_STW     XcoreInsn = 0x6c
	XCORE_INS_SUB     XcoreInsn = 0x6d
	XCORE_INS_SYNCR   XcoreInsn = 0x6e
	XCORE_INS_TESTCT  XcoreInsn = 0x6f
	XCORE_INS_TESTLCL XcoreInsn = 0x70
	XCORE_INS_TESTWCT XcoreInsn = 0x71
	XCORE_INS_TSETMR  XcoreInsn = 0x72
	XCORE_INS_START   XcoreInsn = 0x73
	XCORE_INS_WAITEF  XcoreInsn = 0x74
	XCORE_INS_WAITET  XcoreInsn = 0x75
	XCORE_INS_WAITEU  XcoreInsn = 0x76
	XCORE_INS_XOR     XcoreInsn = 0x77
	XCORE_INS_ZEXT    XcoreInsn = 0x78
	XCORE_INS_ENDING  XcoreInsn = 0x79
)

type XcoreInsnGroup uint32

const (
	XCORE_GRP_INVALID XcoreInsnGroup = 0x0
	XCORE_GRP_JUMP    XcoreInsnGroup = 0x1
	XCORE_GRP_ENDING  XcoreInsnGroup = 0x2
)

type XcoreOpType uint32

const (
	XCORE_OP_INVALID XcoreOpType = 0x0
	XCORE_OP_REG     XcoreOpType = 0x1
	XCORE_OP_IMM     XcoreOpType = 0x2
	XCORE_OP_MEM     XcoreOpType = 0x3
)

type XcoreReg uint32

const (
	XCORE_REG_INVALID XcoreReg = 0x0
	XCORE_REG_CP      XcoreReg = 0x1
	XCORE_REG_DP      XcoreReg = 0x2
	XCORE_REG_LR      XcoreReg = 0x3
	XCORE_REG_SP      XcoreReg = 0x4
	XCORE_REG_R0      XcoreReg = 0x5
	XCORE_REG_R1      XcoreReg = 0x6
	XCORE_REG_R2      XcoreReg = 0x7
	XCORE_REG_R3      XcoreReg = 0x8
	XCORE_REG_R4      XcoreReg = 0x9
	XCORE_REG_R5      XcoreReg = 0xa
	XCORE_REG_R6      XcoreReg = 0xb
	XCORE_REG_R7      XcoreReg = 0xc
	XCORE_REG_R8      XcoreReg = 0xd
	XCORE_REG_R9      XcoreReg = 0xe
	XCORE_REG_R10     XcoreReg = 0xf
	XCORE_REG_R11     XcoreReg = 0x10
	XCORE_REG_PC      XcoreReg = 0x11
	XCORE_REG_SCP     XcoreReg = 0x12
	XCORE_REG_SSR     XcoreReg = 0x13
	XCORE_REG_ET      XcoreReg = 0x14
	XCORE_REG_ED      XcoreReg = 0x15
	XCORE_REG_SED     XcoreReg = 0x16
	XCORE_REG_KEP     XcoreReg = 0x17
	XCORE_REG_KSP     XcoreReg = 0x18
	XCORE_REG_ID      XcoreReg = 0x19
	XCORE_REG_ENDING  XcoreReg = 0x1a
)

type CsXcore struct {
	Count    uint8
	Operands [8]CsXcoreOp
}

type CsXcoreOp struct {
	Type uint32
	Reg  uint32
	_    [8]byte
}

type XcoreOpMem struct {
	Base   uint8
	Index  uint8
	Disp   int32
	Direct int32
}
