// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs sparc_unix.go

package capstone

type SparcCc uint32

const (
	SPARC_CC_INVALID SparcCc = 0x0
	SPARC_CC_ICC_A   SparcCc = 0x108
	SPARC_CC_ICC_N   SparcCc = 0x100
	SPARC_CC_ICC_NE  SparcCc = 0x109
	SPARC_CC_ICC_E   SparcCc = 0x101
	SPARC_CC_ICC_G   SparcCc = 0x10a
	SPARC_CC_ICC_LE  SparcCc = 0x102
	SPARC_CC_ICC_GE  SparcCc = 0x10b
	SPARC_CC_ICC_L   SparcCc = 0x103
	SPARC_CC_ICC_GU  SparcCc = 0x10c
	SPARC_CC_ICC_LEU SparcCc = 0x104
	SPARC_CC_ICC_CC  SparcCc = 0x10d
	SPARC_CC_ICC_CS  SparcCc = 0x105
	SPARC_CC_ICC_POS SparcCc = 0x10e
	SPARC_CC_ICC_NEG SparcCc = 0x106
	SPARC_CC_ICC_VC  SparcCc = 0x10f
	SPARC_CC_ICC_VS  SparcCc = 0x107
	SPARC_CC_FCC_A   SparcCc = 0x118
	SPARC_CC_FCC_N   SparcCc = 0x110
	SPARC_CC_FCC_U   SparcCc = 0x117
	SPARC_CC_FCC_G   SparcCc = 0x116
	SPARC_CC_FCC_UG  SparcCc = 0x115
	SPARC_CC_FCC_L   SparcCc = 0x114
	SPARC_CC_FCC_UL  SparcCc = 0x113
	SPARC_CC_FCC_LG  SparcCc = 0x112
	SPARC_CC_FCC_NE  SparcCc = 0x111
	SPARC_CC_FCC_E   SparcCc = 0x119
	SPARC_CC_FCC_UE  SparcCc = 0x11a
	SPARC_CC_FCC_GE  SparcCc = 0x11b
	SPARC_CC_FCC_UGE SparcCc = 0x11c
	SPARC_CC_FCC_LE  SparcCc = 0x11d
	SPARC_CC_FCC_ULE SparcCc = 0x11e
	SPARC_CC_FCC_O   SparcCc = 0x11f
)

type SparcHint uint32

const (
	SPARC_HINT_INVALID SparcHint = 0x0
	SPARC_HINT_A       SparcHint = 0x1
	SPARC_HINT_PT      SparcHint = 0x2
	SPARC_HINT_PN      SparcHint = 0x4
)

type SparcInsn uint32

const (
	SPARC_INS_INVALID     SparcInsn = 0x0
	SPARC_INS_ADDCC       SparcInsn = 0x1
	SPARC_INS_ADDX        SparcInsn = 0x2
	SPARC_INS_ADDXCC      SparcInsn = 0x3
	SPARC_INS_ADDXC       SparcInsn = 0x4
	SPARC_INS_ADDXCCC     SparcInsn = 0x5
	SPARC_INS_ADD         SparcInsn = 0x6
	SPARC_INS_ALIGNADDR   SparcInsn = 0x7
	SPARC_INS_ALIGNADDRL  SparcInsn = 0x8
	SPARC_INS_ANDCC       SparcInsn = 0x9
	SPARC_INS_ANDNCC      SparcInsn = 0xa
	SPARC_INS_ANDN        SparcInsn = 0xb
	SPARC_INS_AND         SparcInsn = 0xc
	SPARC_INS_ARRAY16     SparcInsn = 0xd
	SPARC_INS_ARRAY32     SparcInsn = 0xe
	SPARC_INS_ARRAY8      SparcInsn = 0xf
	SPARC_INS_B           SparcInsn = 0x10
	SPARC_INS_JMP         SparcInsn = 0x11
	SPARC_INS_BMASK       SparcInsn = 0x12
	SPARC_INS_FB          SparcInsn = 0x13
	SPARC_INS_BRGEZ       SparcInsn = 0x14
	SPARC_INS_BRGZ        SparcInsn = 0x15
	SPARC_INS_BRLEZ       SparcInsn = 0x16
	SPARC_INS_BRLZ        SparcInsn = 0x17
	SPARC_INS_BRNZ        SparcInsn = 0x18
	SPARC_INS_BRZ         SparcInsn = 0x19
	SPARC_INS_BSHUFFLE    SparcInsn = 0x1a
	SPARC_INS_CALL        SparcInsn = 0x1b
	SPARC_INS_CASX        SparcInsn = 0x1c
	SPARC_INS_CAS         SparcInsn = 0x1d
	SPARC_INS_CMASK16     SparcInsn = 0x1e
	SPARC_INS_CMASK32     SparcInsn = 0x1f
	SPARC_INS_CMASK8      SparcInsn = 0x20
	SPARC_INS_CMP         SparcInsn = 0x21
	SPARC_INS_EDGE16      SparcInsn = 0x22
	SPARC_INS_EDGE16L     SparcInsn = 0x23
	SPARC_INS_EDGE16LN    SparcInsn = 0x24
	SPARC_INS_EDGE16N     SparcInsn = 0x25
	SPARC_INS_EDGE32      SparcInsn = 0x26
	SPARC_INS_EDGE32L     SparcInsn = 0x27
	SPARC_INS_EDGE32LN    SparcInsn = 0x28
	SPARC_INS_EDGE32N     SparcInsn = 0x29
	SPARC_INS_EDGE8       SparcInsn = 0x2a
	SPARC_INS_EDGE8L      SparcInsn = 0x2b
	SPARC_INS_EDGE8LN     SparcInsn = 0x2c
	SPARC_INS_EDGE8N      SparcInsn = 0x2d
	SPARC_INS_FABSD       SparcInsn = 0x2e
	SPARC_INS_FABSQ       SparcInsn = 0x2f
	SPARC_INS_FABSS       SparcInsn = 0x30
	SPARC_INS_FADDD       SparcInsn = 0x31
	SPARC_INS_FADDQ       SparcInsn = 0x32
	SPARC_INS_FADDS       SparcInsn = 0x33
	SPARC_INS_FALIGNDATA  SparcInsn = 0x34
	SPARC_INS_FAND        SparcInsn = 0x35
	SPARC_INS_FANDNOT1    SparcInsn = 0x36
	SPARC_INS_FANDNOT1S   SparcInsn = 0x37
	SPARC_INS_FANDNOT2    SparcInsn = 0x38
	SPARC_INS_FANDNOT2S   SparcInsn = 0x39
	SPARC_INS_FANDS       SparcInsn = 0x3a
	SPARC_INS_FCHKSM16    SparcInsn = 0x3b
	SPARC_INS_FCMPD       SparcInsn = 0x3c
	SPARC_INS_FCMPEQ16    SparcInsn = 0x3d
	SPARC_INS_FCMPEQ32    SparcInsn = 0x3e
	SPARC_INS_FCMPGT16    SparcInsn = 0x3f
	SPARC_INS_FCMPGT32    SparcInsn = 0x40
	SPARC_INS_FCMPLE16    SparcInsn = 0x41
	SPARC_INS_FCMPLE32    SparcInsn = 0x42
	SPARC_INS_FCMPNE16    SparcInsn = 0x43
	SPARC_INS_FCMPNE32    SparcInsn = 0x44
	SPARC_INS_FCMPQ       SparcInsn = 0x45
	SPARC_INS_FCMPS       SparcInsn = 0x46
	SPARC_INS_FDIVD       SparcInsn = 0x47
	SPARC_INS_FDIVQ       SparcInsn = 0x48
	SPARC_INS_FDIVS       SparcInsn = 0x49
	SPARC_INS_FDMULQ      SparcInsn = 0x4a
	SPARC_INS_FDTOI       SparcInsn = 0x4b
	SPARC_INS_FDTOQ       SparcInsn = 0x4c
	SPARC_INS_FDTOS       SparcInsn = 0x4d
	SPARC_INS_FDTOX       SparcInsn = 0x4e
	SPARC_INS_FEXPAND     SparcInsn = 0x4f
	SPARC_INS_FHADDD      SparcInsn = 0x50
	SPARC_INS_FHADDS      SparcInsn = 0x51
	SPARC_INS_FHSUBD      SparcInsn = 0x52
	SPARC_INS_FHSUBS      SparcInsn = 0x53
	SPARC_INS_FITOD       SparcInsn = 0x54
	SPARC_INS_FITOQ       SparcInsn = 0x55
	SPARC_INS_FITOS       SparcInsn = 0x56
	SPARC_INS_FLCMPD      SparcInsn = 0x57
	SPARC_INS_FLCMPS      SparcInsn = 0x58
	SPARC_INS_FLUSHW      SparcInsn = 0x59
	SPARC_INS_FMEAN16     SparcInsn = 0x5a
	SPARC_INS_FMOVD       SparcInsn = 0x5b
	SPARC_INS_FMOVQ       SparcInsn = 0x5c
	SPARC_INS_FMOVRDGEZ   SparcInsn = 0x5d
	SPARC_INS_FMOVRQGEZ   SparcInsn = 0x5e
	SPARC_INS_FMOVRSGEZ   SparcInsn = 0x5f
	SPARC_INS_FMOVRDGZ    SparcInsn = 0x60
	SPARC_INS_FMOVRQGZ    SparcInsn = 0x61
	SPARC_INS_FMOVRSGZ    SparcInsn = 0x62
	SPARC_INS_FMOVRDLEZ   SparcInsn = 0x63
	SPARC_INS_FMOVRQLEZ   SparcInsn = 0x64
	SPARC_INS_FMOVRSLEZ   SparcInsn = 0x65
	SPARC_INS_FMOVRDLZ    SparcInsn = 0x66
	SPARC_INS_FMOVRQLZ    SparcInsn = 0x67
	SPARC_INS_FMOVRSLZ    SparcInsn = 0x68
	SPARC_INS_FMOVRDNZ    SparcInsn = 0x69
	SPARC_INS_FMOVRQNZ    SparcInsn = 0x6a
	SPARC_INS_FMOVRSNZ    SparcInsn = 0x6b
	SPARC_INS_FMOVRDZ     SparcInsn = 0x6c
	SPARC_INS_FMOVRQZ     SparcInsn = 0x6d
	SPARC_INS_FMOVRSZ     SparcInsn = 0x6e
	SPARC_INS_FMOVS       SparcInsn = 0x6f
	SPARC_INS_FMUL8SUX16  SparcInsn = 0x70
	SPARC_INS_FMUL8ULX16  SparcInsn = 0x71
	SPARC_INS_FMUL8X16    SparcInsn = 0x72
	SPARC_INS_FMUL8X16AL  SparcInsn = 0x73
	SPARC_INS_FMUL8X16AU  SparcInsn = 0x74
	SPARC_INS_FMULD       SparcInsn = 0x75
	SPARC_INS_FMULD8SUX16 SparcInsn = 0x76
	SPARC_INS_FMULD8ULX16 SparcInsn = 0x77
	SPARC_INS_FMULQ       SparcInsn = 0x78
	SPARC_INS_FMULS       SparcInsn = 0x79
	SPARC_INS_FNADDD      SparcInsn = 0x7a
	SPARC_INS_FNADDS      SparcInsn = 0x7b
	SPARC_INS_FNAND       SparcInsn = 0x7c
	SPARC_INS_FNANDS      SparcInsn = 0x7d
	SPARC_INS_FNEGD       SparcInsn = 0x7e
	SPARC_INS_FNEGQ       SparcInsn = 0x7f
	SPARC_INS_FNEGS       SparcInsn = 0x80
	SPARC_INS_FNHADDD     SparcInsn = 0x81
	SPARC_INS_FNHADDS     SparcInsn = 0x82
	SPARC_INS_FNOR        SparcInsn = 0x83
	SPARC_INS_FNORS       SparcInsn = 0x84
	SPARC_INS_FNOT1       SparcInsn = 0x85
	SPARC_INS_FNOT1S      SparcInsn = 0x86
	SPARC_INS_FNOT2       SparcInsn = 0x87
	SPARC_INS_FNOT2S      SparcInsn = 0x88
	SPARC_INS_FONE        SparcInsn = 0x89
	SPARC_INS_FONES       SparcInsn = 0x8a
	SPARC_INS_FOR         SparcInsn = 0x8b
	SPARC_INS_FORNOT1     SparcInsn = 0x8c
	SPARC_INS_FORNOT1S    SparcInsn = 0x8d
	SPARC_INS_FORNOT2     SparcInsn = 0x8e
	SPARC_INS_FORNOT2S    SparcInsn = 0x8f
	SPARC_INS_FORS        SparcInsn = 0x90
	SPARC_INS_FPACK16     SparcInsn = 0x91
	SPARC_INS_FPACK32     SparcInsn = 0x92
	SPARC_INS_FPACKFIX    SparcInsn = 0x93
	SPARC_INS_FPADD16     SparcInsn = 0x94
	SPARC_INS_FPADD16S    SparcInsn = 0x95
	SPARC_INS_FPADD32     SparcInsn = 0x96
	SPARC_INS_FPADD32S    SparcInsn = 0x97
	SPARC_INS_FPADD64     SparcInsn = 0x98
	SPARC_INS_FPMERGE     SparcInsn = 0x99
	SPARC_INS_FPSUB16     SparcInsn = 0x9a
	SPARC_INS_FPSUB16S    SparcInsn = 0x9b
	SPARC_INS_FPSUB32     SparcInsn = 0x9c
	SPARC_INS_FPSUB32S    SparcInsn = 0x9d
	SPARC_INS_FQTOD       SparcInsn = 0x9e
	SPARC_INS_FQTOI       SparcInsn = 0x9f
	SPARC_INS_FQTOS       SparcInsn = 0xa0
	SPARC_INS_FQTOX       SparcInsn = 0xa1
	SPARC_INS_FSLAS16     SparcInsn = 0xa2
	SPARC_INS_FSLAS32     SparcInsn = 0xa3
	SPARC_INS_FSLL16      SparcInsn = 0xa4
	SPARC_INS_FSLL32      SparcInsn = 0xa5
	SPARC_INS_FSMULD      SparcInsn = 0xa6
	SPARC_INS_FSQRTD      SparcInsn = 0xa7
	SPARC_INS_FSQRTQ      SparcInsn = 0xa8
	SPARC_INS_FSQRTS      SparcInsn = 0xa9
	SPARC_INS_FSRA16      SparcInsn = 0xaa
	SPARC_INS_FSRA32      SparcInsn = 0xab
	SPARC_INS_FSRC1       SparcInsn = 0xac
	SPARC_INS_FSRC1S      SparcInsn = 0xad
	SPARC_INS_FSRC2       SparcInsn = 0xae
	SPARC_INS_FSRC2S      SparcInsn = 0xaf
	SPARC_INS_FSRL16      SparcInsn = 0xb0
	SPARC_INS_FSRL32      SparcInsn = 0xb1
	SPARC_INS_FSTOD       SparcInsn = 0xb2
	SPARC_INS_FSTOI       SparcInsn = 0xb3
	SPARC_INS_FSTOQ       SparcInsn = 0xb4
	SPARC_INS_FSTOX       SparcInsn = 0xb5
	SPARC_INS_FSUBD       SparcInsn = 0xb6
	SPARC_INS_FSUBQ       SparcInsn = 0xb7
	SPARC_INS_FSUBS       SparcInsn = 0xb8
	SPARC_INS_FXNOR       SparcInsn = 0xb9
	SPARC_INS_FXNORS      SparcInsn = 0xba
	SPARC_INS_FXOR        SparcInsn = 0xbb
	SPARC_INS_FXORS       SparcInsn = 0xbc
	SPARC_INS_FXTOD       SparcInsn = 0xbd
	SPARC_INS_FXTOQ       SparcInsn = 0xbe
	SPARC_INS_FXTOS       SparcInsn = 0xbf
	SPARC_INS_FZERO       SparcInsn = 0xc0
	SPARC_INS_FZEROS      SparcInsn = 0xc1
	SPARC_INS_JMPL        SparcInsn = 0xc2
	SPARC_INS_LDD         SparcInsn = 0xc3
	SPARC_INS_LD          SparcInsn = 0xc4
	SPARC_INS_LDQ         SparcInsn = 0xc5
	SPARC_INS_LDSB        SparcInsn = 0xc6
	SPARC_INS_LDSH        SparcInsn = 0xc7
	SPARC_INS_LDSW        SparcInsn = 0xc8
	SPARC_INS_LDUB        SparcInsn = 0xc9
	SPARC_INS_LDUH        SparcInsn = 0xca
	SPARC_INS_LDX         SparcInsn = 0xcb
	SPARC_INS_LZCNT       SparcInsn = 0xcc
	SPARC_INS_MEMBAR      SparcInsn = 0xcd
	SPARC_INS_MOVDTOX     SparcInsn = 0xce
	SPARC_INS_MOV         SparcInsn = 0xcf
	SPARC_INS_MOVRGEZ     SparcInsn = 0xd0
	SPARC_INS_MOVRGZ      SparcInsn = 0xd1
	SPARC_INS_MOVRLEZ     SparcInsn = 0xd2
	SPARC_INS_MOVRLZ      SparcInsn = 0xd3
	SPARC_INS_MOVRNZ      SparcInsn = 0xd4
	SPARC_INS_MOVRZ       SparcInsn = 0xd5
	SPARC_INS_MOVSTOSW    SparcInsn = 0xd6
	SPARC_INS_MOVSTOUW    SparcInsn = 0xd7
	SPARC_INS_MULX        SparcInsn = 0xd8
	SPARC_INS_NOP         SparcInsn = 0xd9
	SPARC_INS_ORCC        SparcInsn = 0xda
	SPARC_INS_ORNCC       SparcInsn = 0xdb
	SPARC_INS_ORN         SparcInsn = 0xdc
	SPARC_INS_OR          SparcInsn = 0xdd
	SPARC_INS_PDIST       SparcInsn = 0xde
	SPARC_INS_PDISTN      SparcInsn = 0xdf
	SPARC_INS_POPC        SparcInsn = 0xe0
	SPARC_INS_RD          SparcInsn = 0xe1
	SPARC_INS_RESTORE     SparcInsn = 0xe2
	SPARC_INS_RETT        SparcInsn = 0xe3
	SPARC_INS_SAVE        SparcInsn = 0xe4
	SPARC_INS_SDIVCC      SparcInsn = 0xe5
	SPARC_INS_SDIVX       SparcInsn = 0xe6
	SPARC_INS_SDIV        SparcInsn = 0xe7
	SPARC_INS_SETHI       SparcInsn = 0xe8
	SPARC_INS_SHUTDOWN    SparcInsn = 0xe9
	SPARC_INS_SIAM        SparcInsn = 0xea
	SPARC_INS_SLLX        SparcInsn = 0xeb
	SPARC_INS_SLL         SparcInsn = 0xec
	SPARC_INS_SMULCC      SparcInsn = 0xed
	SPARC_INS_SMUL        SparcInsn = 0xee
	SPARC_INS_SRAX        SparcInsn = 0xef
	SPARC_INS_SRA         SparcInsn = 0xf0
	SPARC_INS_SRLX        SparcInsn = 0xf1
	SPARC_INS_SRL         SparcInsn = 0xf2
	SPARC_INS_STBAR       SparcInsn = 0xf3
	SPARC_INS_STB         SparcInsn = 0xf4
	SPARC_INS_STD         SparcInsn = 0xf5
	SPARC_INS_ST          SparcInsn = 0xf6
	SPARC_INS_STH         SparcInsn = 0xf7
	SPARC_INS_STQ         SparcInsn = 0xf8
	SPARC_INS_STX         SparcInsn = 0xf9
	SPARC_INS_SUBCC       SparcInsn = 0xfa
	SPARC_INS_SUBX        SparcInsn = 0xfb
	SPARC_INS_SUBXCC      SparcInsn = 0xfc
	SPARC_INS_SUB         SparcInsn = 0xfd
	SPARC_INS_SWAP        SparcInsn = 0xfe
	SPARC_INS_TADDCCTV    SparcInsn = 0xff
	SPARC_INS_TADDCC      SparcInsn = 0x100
	SPARC_INS_T           SparcInsn = 0x101
	SPARC_INS_TSUBCCTV    SparcInsn = 0x102
	SPARC_INS_TSUBCC      SparcInsn = 0x103
	SPARC_INS_UDIVCC      SparcInsn = 0x104
	SPARC_INS_UDIVX       SparcInsn = 0x105
	SPARC_INS_UDIV        SparcInsn = 0x106
	SPARC_INS_UMULCC      SparcInsn = 0x107
	SPARC_INS_UMULXHI     SparcInsn = 0x108
	SPARC_INS_UMUL        SparcInsn = 0x109
	SPARC_INS_UNIMP       SparcInsn = 0x10a
	SPARC_INS_FCMPED      SparcInsn = 0x10b
	SPARC_INS_FCMPEQ      SparcInsn = 0x10c
	SPARC_INS_FCMPES      SparcInsn = 0x10d
	SPARC_INS_WR          SparcInsn = 0x10e
	SPARC_INS_XMULX       SparcInsn = 0x10f
	SPARC_INS_XMULXHI     SparcInsn = 0x110
	SPARC_INS_XNORCC      SparcInsn = 0x111
	SPARC_INS_XNOR        SparcInsn = 0x112
	SPARC_INS_XORCC       SparcInsn = 0x113
	SPARC_INS_XOR         SparcInsn = 0x114
	SPARC_INS_RET         SparcInsn = 0x115
	SPARC_INS_RETL        SparcInsn = 0x116
	SPARC_INS_ENDING      SparcInsn = 0x117
)

type SparcInsnGroup uint32

const (
	SPARC_GRP_INVALID  SparcInsnGroup = 0x0
	SPARC_GRP_JUMP     SparcInsnGroup = 0x1
	SPARC_GRP_HARDQUAD SparcInsnGroup = 0x80
	SPARC_GRP_V9       SparcInsnGroup = 0x81
	SPARC_GRP_VIS      SparcInsnGroup = 0x82
	SPARC_GRP_VIS2     SparcInsnGroup = 0x83
	SPARC_GRP_VIS3     SparcInsnGroup = 0x84
	SPARC_GRP_32BIT    SparcInsnGroup = 0x85
	SPARC_GRP_64BIT    SparcInsnGroup = 0x86
	SPARC_GRP_ENDING   SparcInsnGroup = 0x87
)

type SparcOpType uint32

const (
	SPARC_OP_INVALID SparcOpType = 0x0
	SPARC_OP_REG     SparcOpType = 0x1
	SPARC_OP_IMM     SparcOpType = 0x2
	SPARC_OP_MEM     SparcOpType = 0x3
)

type SparcReg uint32

const (
	SPARC_REG_INVALID SparcReg = 0x0
	SPARC_REG_F0      SparcReg = 0x1
	SPARC_REG_F1      SparcReg = 0x2
	SPARC_REG_F2      SparcReg = 0x3
	SPARC_REG_F3      SparcReg = 0x4
	SPARC_REG_F4      SparcReg = 0x5
	SPARC_REG_F5      SparcReg = 0x6
	SPARC_REG_F6      SparcReg = 0x7
	SPARC_REG_F7      SparcReg = 0x8
	SPARC_REG_F8      SparcReg = 0x9
	SPARC_REG_F9      SparcReg = 0xa
	SPARC_REG_F10     SparcReg = 0xb
	SPARC_REG_F11     SparcReg = 0xc
	SPARC_REG_F12     SparcReg = 0xd
	SPARC_REG_F13     SparcReg = 0xe
	SPARC_REG_F14     SparcReg = 0xf
	SPARC_REG_F15     SparcReg = 0x10
	SPARC_REG_F16     SparcReg = 0x11
	SPARC_REG_F17     SparcReg = 0x12
	SPARC_REG_F18     SparcReg = 0x13
	SPARC_REG_F19     SparcReg = 0x14
	SPARC_REG_F20     SparcReg = 0x15
	SPARC_REG_F21     SparcReg = 0x16
	SPARC_REG_F22     SparcReg = 0x17
	SPARC_REG_F23     SparcReg = 0x18
	SPARC_REG_F24     SparcReg = 0x19
	SPARC_REG_F25     SparcReg = 0x1a
	SPARC_REG_F26     SparcReg = 0x1b
	SPARC_REG_F27     SparcReg = 0x1c
	SPARC_REG_F28     SparcReg = 0x1d
	SPARC_REG_F29     SparcReg = 0x1e
	SPARC_REG_F30     SparcReg = 0x1f
	SPARC_REG_F31     SparcReg = 0x20
	SPARC_REG_F32     SparcReg = 0x21
	SPARC_REG_F34     SparcReg = 0x22
	SPARC_REG_F36     SparcReg = 0x23
	SPARC_REG_F38     SparcReg = 0x24
	SPARC_REG_F40     SparcReg = 0x25
	SPARC_REG_F42     SparcReg = 0x26
	SPARC_REG_F44     SparcReg = 0x27
	SPARC_REG_F46     SparcReg = 0x28
	SPARC_REG_F48     SparcReg = 0x29
	SPARC_REG_F50     SparcReg = 0x2a
	SPARC_REG_F52     SparcReg = 0x2b
	SPARC_REG_F54     SparcReg = 0x2c
	SPARC_REG_F56     SparcReg = 0x2d
	SPARC_REG_F58     SparcReg = 0x2e
	SPARC_REG_F60     SparcReg = 0x2f
	SPARC_REG_F62     SparcReg = 0x30
	SPARC_REG_FCC0    SparcReg = 0x31
	SPARC_REG_FCC1    SparcReg = 0x32
	SPARC_REG_FCC2    SparcReg = 0x33
	SPARC_REG_FCC3    SparcReg = 0x34
	SPARC_REG_FP      SparcReg = 0x35
	SPARC_REG_G0      SparcReg = 0x36
	SPARC_REG_G1      SparcReg = 0x37
	SPARC_REG_G2      SparcReg = 0x38
	SPARC_REG_G3      SparcReg = 0x39
	SPARC_REG_G4      SparcReg = 0x3a
	SPARC_REG_G5      SparcReg = 0x3b
	SPARC_REG_G6      SparcReg = 0x3c
	SPARC_REG_G7      SparcReg = 0x3d
	SPARC_REG_I0      SparcReg = 0x3e
	SPARC_REG_I1      SparcReg = 0x3f
	SPARC_REG_I2      SparcReg = 0x40
	SPARC_REG_I3      SparcReg = 0x41
	SPARC_REG_I4      SparcReg = 0x42
	SPARC_REG_I5      SparcReg = 0x43
	SPARC_REG_I7      SparcReg = 0x44
	SPARC_REG_ICC     SparcReg = 0x45
	SPARC_REG_L0      SparcReg = 0x46
	SPARC_REG_L1      SparcReg = 0x47
	SPARC_REG_L2      SparcReg = 0x48
	SPARC_REG_L3      SparcReg = 0x49
	SPARC_REG_L4      SparcReg = 0x4a
	SPARC_REG_L5      SparcReg = 0x4b
	SPARC_REG_L6      SparcReg = 0x4c
	SPARC_REG_L7      SparcReg = 0x4d
	SPARC_REG_O0      SparcReg = 0x4e
	SPARC_REG_O1      SparcReg = 0x4f
	SPARC_REG_O2      SparcReg = 0x50
	SPARC_REG_O3      SparcReg = 0x51
	SPARC_REG_O4      SparcReg = 0x52
	SPARC_REG_O5      SparcReg = 0x53
	SPARC_REG_O7      SparcReg = 0x54
	SPARC_REG_SP      SparcReg = 0x55
	SPARC_REG_Y       SparcReg = 0x56
	SPARC_REG_XCC     SparcReg = 0x57
	SPARC_REG_ENDING  SparcReg = 0x58
	SPARC_REG_O6      SparcReg = 0x55
	SPARC_REG_I6      SparcReg = 0x35
)

type CsSparc struct {
	Cc       uint32
	Hint     uint32
	Count    uint8
	_        [4]byte
	Operands [4]CsSparcOp
}

type CsSparcOp struct {
	Type uint32
	_    [4]byte
	Reg  uint32
	_    [4]byte
}

type SparcOpMem struct {
	Base  uint8
	Index uint8
	Disp  int32
}
